### ISSUE TITLE
Cannot load extension: missing dependencies

### ISSUE THREAD

**Issue by colinemondswieprecht** [supabase-community/supabase-vscode-extension#2]
Hey,

I found your extension via the recent Launch Week Hackathon, and it looks really useful.

Unfortunately, it doesn't seem to install properly. I tried installing it via the VS Code marketplace, but it fails when trying to load:

```
2024-02-22 09:49:01.186 [error] Activating extension anasaraid.vscode-supabase-cli failed due to an error:
2024-02-22 09:49:01.186 [error] Error: Cannot find module 'axios'
```

Apparently it requires an additional NodeJS module? Should it not be shipping with that?

It seems the issue can be fixed by manually entering the installed extension's directory and running `npm run install:all`, but that seems a little bit ridiculous.

For anyone else with this problem looking for a quick fix, on Windows, the incantations are:
```
# npm install --global yarn
cd $env:userprofile\.vscode\extensions\anasaraid.vscode-supabase-cli-*
npm run install:all
```

**Comment by anas-araid** [comment]
hey @colinemondswieprecht! thanks for the interest!

i've just fixed the production build, can you try now if you can install it from the vscode marketplace?

**Comment by colinemondswieprecht** [comment]
Issue is fixed. Thank you!
