### ISSUE TITLE
Sort DB Functions by name

### ISSUE THREAD

**Issue by ale24dev** [supabase-community/supabase-vscode-extension#23]
## Description

It would be very beneficial to sort the `DB Functions` by name. This change would make it much easier to locate specific functions, improving overall usability and efficiency.

### Demonstration

![Screenshot 2024-09-01 at 2 19 27 AM](https://github.com/user-attachments/assets/bf8cebdb-6977-40c1-ac60-f73252623a8a)

**Comment by thorwebdev** [comment]
Will be included in next release. Thank you!
